name: Main CI

on:
  pull_request:
    branches:
      - master
      - releases/**
  push:
    branches:
      - master
      - releases/**
      - feat/**

jobs:
  reusable_workflow_job:
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]
        node-version: [14.x, 16.x, 18.x]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps: 
      - uses: trivonhan/github-action-test/.github/workflows/nodejs.yml@master
        with:
          package_manager: 'yarn'
