name: Main CI

on:
  workflow_call:
    inputs:
      language: 
        required: true
        type: string
      package_manager:
        required: false
        type: string

jobs:
  nodejs_ci:
    if: ${{ inputs.language == 'nodejs' }}
    uses: trivonhan/github-action-test/.github/workflows/nodejs.yml@master
    with:
      package_manager: ${{ inputs.package_manager }}
  go_ci:
    if: ${{ inputs.language == 'go' }}
    uses: trivonhan/github-action-test/.github/workflows/go.yml@master    
