name: Main CI

on:
  pull_request:
    branches:
      - master
      - releases/**
  push:
    branches:
      - master
      - releases/**
      - feat/**

jobs:
  reusable_workflow_job:
    uses: trivonhan/github-action-test/.github/workflows/nodejs.yml@master
    with:
      package_manager: 'pnpm'
      
