name: Master CI

on:
  pull_request:
    branches:
      - master
      - releases/**
  push:
    branches:
      - master
      - releases/**
      - feat/**
jobs:
  nodejs_ci:
    uses: trivonhan/github-action-test/.github/workflows/main.yml@master
    with:
      language: 'nodejs'
      package_manager: 'pnpm'