name: Master CI

on:
  push:
    tags:
      - v*
    branches:
      - master
      - main
      - feat/**
  pull_request:
  
jobs:
  nodejs_ci:
    uses: trivonhan/github-action-test/.github/workflows/main.yml@master
    with:
      language: 'nodejs'
      package_manager: 'pnpm'